'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import GlobalThemeProvider from "@/theme/global.theme";
import { StoreProvider } from "@/app/StoreProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { PersistGate } from "redux-persist/integration/react";
import { ToastContainer } from "react-toastify";
import { persistor } from "@/lib/configStore";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <PersistGate loading={null} persistor={persistor}>
            <GlobalThemeProvider>{children}</GlobalThemeProvider>
            <ToastContainer />
          </PersistGate>
        </StoreProvider>
      </body>
    </html>
  );
}
